### ISSUE TITLE
Confirm all location / addresses in the system geocode and pin to map

### ISSUE THREAD

**Issue by deld** [BaltimoreCity/BaltimoreTechWebsite#16]
Making sure that events from meetups, other events, organization addresses, etc all geocode so they can be plotted on the map.

**Comment by no13000** [comment]
In the design, the map only exist in "Upcoming events" page. Do you mean to plot all locations (events, org) in that page (Upcoming events) or have a separate map that plot only organizations addresses in "Organizations" own page?

**Comment by deld** [comment]
I like on the explore page pulling in everything (people, orgs, events, meetups, etc) anything that can be plotted are plotted on a map with a few more items added to the legend...then having things filterable, etc and when you hover over a pin the element below highlights, and vise versa.  

<img width="591" alt="screenshot 2019-01-25 10 43 07" src="https://user-images.githubusercontent.com/3333445/51756064-26358f80-208e-11e9-8a42-025ab89252e1.png">

**Comment by no13000** [comment]
Working on this, will submit tomorrow. Sorry for the delay!
