### ISSUE TITLE
CI/CD and push to github pages

### ISSUE THREAD

**Issue by deld** [BaltimoreCity/BaltimoreTechWebsite#19]
Configure CI/CD with CircleCI and push to github pages.

**Comment by no13000** [comment]
@deld need your help to enable GitHub Pages through repository's Settings > Options > GitHub Pages

**Comment by deld** [comment]
This doesn't seem to be done....see here

**Comment by no13000** [comment]
@deld are you able to select a source from the dropdown under "Source"? From my forked repository, I can select "master branch" from Source and once saved, github will automatically host my repository and provide me a url.

**Comment by deld** [comment]
What should I select as the source @no13000 ? 
![screenshot 2019-01-30 06 51 34](https://user-images.githubusercontent.com/3333445/51979596-85631d80-245b-11e9-8db1-4ef42baf4fee.png)

**Comment by deld** [comment]
done @no13000 its pushing it here -  https://baltimorecity.github.io/BaltimoreTechWebsite/ but nothing is published yet

**Comment by no13000** [comment]
@deld Thanks! I'll issue an PR soon to fix the styles problem
