### ISSUE TITLE
Integrate the site with forestry.io

### ISSUE THREAD

**Issue by deld** [BaltimoreCity/BaltimoreTechWebsite#2]

**Comment by no13000** [comment]
@deld as a guest in your forestry.io project, I don't have access to configure settings/sidebar. In order to make events data editable from forestry, I need to have access to configure at least the sidebar.

**Comment by deld** [comment]
@no13000 try now, I upgraded the account and gave you developer privileges.... see here for what each role can do.  Let me know if you need more permissions - https://forestry.io/docs/settings/team-management/
