### ISSUE TITLE
Wire up search

### ISSUE THREAD

**Issue by deld** [BaltimoreCity/BaltimoreTechWebsite#27]
Wire up search to use all available data to provide results.

**Comment by no13000** [comment]
working on this along with the pagination

**Comment by no13000** [comment]
@deld I'll have search completed by today, I'll be away for the next few days for lunar new year and will be back on Friday 8 Feb. I'll still be reachable in Slack though.

**Comment by no13000** [comment]
@deld I've finished the search functions and will issue a PR soon. Pagination isn't included in this PR unfortunately cause jekyll-paginate-v2 plugin doesn't support Github Pages atm.. so I'll need to find a workaround for that. Maybe we'll open another issue for pagination and I'll get back to work on it right after holidays, is that fine with you?

**Comment by deld** [comment]
Yeah please open up a new issue for pagination.  If it is a pain to work around the it without the plugin, we can consider hosting it elsewhere if needed.  But if you have time please create the issue and fix it in another branch, we can determine the best place to host when you get back.  Unless you think of an easy work around before that @no13000

**Comment by no13000** [comment]
@deld got it, thanks!!
