### ISSUE TITLE
Create a separate branch and add dummy / sample data for testing

### ISSUE THREAD

**Issue by deld** [BaltimoreCity/BaltimoreTechWebsite#31]
We'll need to pull in data from the old wordpress portal ....mainly the people and companies.  We can do all of this in a separate branch

**Comment by maysam** [comment]
when status is draft, should I ignore them?

`<wp:status><![CDATA[draft]]></wp:status>`

**Comment by maysam** [comment]
should I copy the images or use the link?

http://baltimoretech1.wpengine.com/wp-content/uploads/2015/05/croppedImg_784849923.png

**Comment by maysam** [comment]
should I also import the category and meta data?

**Comment by maysam** [comment]
draft companies miss lots of data, so I might just ignore them, unless instructed otherwise

**Comment by deld** [comment]
> should I copy the images or use the link?
> 
> http://baltimoretech1.wpengine.com/wp-content/uploads/2015/05/croppedImg_784849923.png

link is fine for now....but note, when we turn off the WP instance they won't work and we'll need people to point to an updated link.  But they are good place holders for the test data

**Comment by maysam** [comment]
@deld I can just download them to the assets folder now, how about that?

**Comment by deld** [comment]
> should I also import the category and meta data?

Let's do two steps, convert the WP output into CSV's then I can inspect and see what other fields may be needed to include in the data files for this site

**Comment by deld** [comment]
> when status is draft, should I ignore them?
> 
> `<wp:status><![CDATA[draft]]></wp:status>`

yes

**Comment by deld** [comment]
> @deld I can just download them to the assets folder now, how about that?

No I wouldn't muddy up that directory with that info for now

**Comment by maysam** [comment]
can we close this? @deld

**Comment by deld** [comment]
yes
