### ISSUE TITLE
Configure CI for testing branch

### ISSUE THREAD

**Issue by deld** [BaltimoreCity/BaltimoreTechWebsite#35]
Set up CircleCI to work with the testing branch to ensure that anything checked in doesn't break the build

**Comment by maysam** [comment]
https://circleci.com/gh/BaltimoreCity/BaltimoreTechWebsite/1

**Comment by maysam** [comment]
This is CI for testing branch This is also circleCI for test data branch https://circleci.com/gh/maysam/BaltimoreTechWebsite/1
