### ISSUE TITLE
Find and add Tech meetups in Baltimore to site

### ISSUE THREAD

**Issue by deld** [BaltimoreCity/BaltimoreTechWebsite#38]
look around meetup.com for meetups in Baltimore City specifically

**Comment by imaurimotorin** [comment]
List of Baltimore Tech Meetups
[https://drive.google.com/file/d/1qmEU_BN1ozIBZBJOWivW9XGhnDYuPi3y/view?usp=sharing](url)

**Comment by deld** [comment]
@maysam @imaurimotorin - Bringing the comms back here....the workflow should be:

1) Register the meetup (lets say in a _data/meetups.yml file)
2) We use the API and "watch" for any events posted to that meetup 
3) This should be done with the following script - https://github.com/BaltimoreCity/meetup-register looking in the BaltimoreTechWebsite meetup data file (in item # 1 above)
4) As events are found in meetup.com they are pulled and written automatically to the events data files - https://github.com/BaltimoreCity/BaltimoreTechWebsite/tree/master/_data/events/2019

Thoughts, comments?

**Comment by maysam** [comment]
1- I have already written a python script that uses meetup api to repopulate the meetup events in _data folder

2- the meetup-register code doest pull data from meetup.com, all it does is to push the data to github

3- where should we setup the crobjob to do this on daily basis?

4- meetup and event are the same to me, but you seem to be using them differently, are you referring to occurrences of a meetup as events? so you want us to collected the events for registered meetups only?

**Comment by deld** [comment]
1) Great
2) It was supposed to pull the meetup id, and CircleCI ran in the background that pulled the data from meetup.com and pushed the data back into the events folder on github
3) Can this be run via CircleCI?
4) Yes I am using them differently...... for example I'd like people to "register" a JavaScript meetup (the group putting it on).  From there we just watch the meetup.com page and pull in all events that meetup hosts automatically.   People can add events manually, but to get the automated pull, we only do that for meetups on meetup.com

**Comment by maysam** [comment]
I'll investigate the possibilities and report back

**Comment by deld** [comment]
ok

**Comment by maysam** [comment]
regarding 3, circleci only runs when there is a push, it cannot be expected to run on regular basis

**Comment by deld** [comment]
Please update the meetup register code to work as expected...we'll figure out how best to trigger it.  Likely as an AWS Lambda @maysam
