### ISSUE TITLE
Set up CI/CD for test data server

### ISSUE THREAD

**Issue by deld** [BaltimoreCity/BaltimoreTechWebsite#40]
Set up server (not sure if you can have multiple github pages in one repo?  But want an easy want to see the site up with the test data (not on the master branch which is production).

**Comment by maysam** [comment]
Should I make a copy in my own github account with the test data branch as master?

**Comment by maysam** [comment]
you can see the test data at https://maysam.github.io/BaltimoreTechWebsite/organizations

**Comment by maysam** [comment]
This is also circleCI for test data branch https://circleci.com/gh/maysam/BaltimoreTechWebsite/1
