### ISSUE TITLE
Merge Events and Upcoming events data structures together 

### ISSUE THREAD

**Issue by deld** [BaltimoreCity/BaltimoreTechWebsite#41]
It's duplicative to have two events files, 

1) merge them into one 
2) Update forestry to use one file
3) Update the code so that for upcoming events it just pulls the next X events into the site.

**Comment by maysam** [comment]
where do we pull the events from?

**Comment by deld** [comment]
pull from here - https://github.com/BaltimoreCity/BaltimoreTechWebsite/tree/master/_data/events/2019

**Comment by maysam** [comment]
@deld 
"Events Calendar" is also not working, right?
![image](https://user-images.githubusercontent.com/591033/54046779-96394880-41ea-11e9-97b5-9cb590b64218.png)

should I fix that too?

**Comment by maysam** [comment]
also year cannot be changed there

**Comment by maysam** [comment]
also since we don't include year in event data, code sees them all in future

![image](https://user-images.githubusercontent.com/591033/54047016-2d9e9b80-41eb-11e9-94fe-f138e316c243.png)

**Comment by maysam** [comment]
@deld 
for now I just make the app to use event tree instead of upcoming events json, until you get back to me with above

**Comment by deld** [comment]
yes I think we need to add the year @maysam
