### ISSUE TITLE
Remove all forms from the site

### ISSUE THREAD

**Issue by deld** [BaltimoreCity/BaltimoreTechWebsite#5]
will no longer be needed

**Comment by no13000** [comment]
should I remove "Post a job" form and other respective UI elements that links to the form too?

**Comment by deld** [comment]
Yes, all of that will be controlled by the data files, correct?

**Comment by no13000** [comment]
> Yes, all of that will be controlled by the data files, correct?
noted

**Comment by no13000** [comment]
consider closing this, fixed in #10  and #14
