### ISSUE TITLE
Confirm search is working across all objects and data types

### ISSUE THREAD

**Issue by deld** [BaltimoreCity/BaltimoreTechWebsite#52]
test and make sure that the search functionality is working

**Comment by maysam** [comment]
I'm rewriting the search function manually so it works in pagination in place, current search only searches in the current page

**Comment by maysam** [comment]
@deld in the events page and front page, do we want to show past events?

**Comment by deld** [comment]
no just future events @maysam

**Comment by maysam** [comment]
just a note here
search is different in events from people and organizations, because the data for people and orgs can be preprocessed, but events should be filtered based on date, so old data are always filtered out
