### ISSUE TITLE
For pull events from meetups

### ISSUE THREAD

**Issue by deld** [BaltimoreCity/BaltimoreTechWebsite#8]
Add the ability for someone to register a meetup.....see if we can make the site smart enough to pull the meetup events (https://www.meetup.com/) into the calendar or events periodically.

**Comment by no13000** [comment]
Will this site eventually have a backend? In order to register a meetup/event or pull meetup events from meetup.com through their API periodically will require a server-side job right?

**Comment by deld** [comment]
you tell me....what are the options to get this done? what are your recommendations for approach?

**Comment by no13000** [comment]
> Any opportunities to create a Lambda job to handle this if needed?

Sounds good, I'll attempt to create a script that can be executed by lambda job to pull data through their (meetup.com) API.

**Comment by deld** [comment]
Or do you see another way to get this done? any other recommendations? if not, what do you anticipate as the workflow:

1) Register meetup (trough the data file)
2) Lambda runs as a cron job and looks up the data files form Github and pulls the event info
3) The Lambda writes to the event data file in github

Is that the flow you anticipate or something else?

**Comment by no13000** [comment]
My anticipation is to create a script that cron job can execute to fetch data from meetup.com through their API and writes the data to event data file that Jekyll can recognize. For the register meetup part, do you mean to let public users to register meetups/events (will write events data file) so it will show on the calendar or events?

**Comment by deld** [comment]
I am thinking perhaps adding a new data type meetups.json where people will add maybe some basic information, then the link to the meetup (or meetup id - if thats needed).  That is what your cron would read then fetch from meetup.com and write the date to the event data file.  Make sense?

**Comment by no13000** [comment]
> I am thinking perhaps adding a new data type meetups.json where people will add maybe some basic information, then the link to the meetup (or meetup id - if thats needed). That is what your cron would read then fetch from meetup.com and write the date to the event data file. Make sense?

sounds good to me

**Comment by no13000** [comment]
> Let me know when you are ready for me to create a new project for your Lambda....I can make it in the same github organization and ideally we get it set up with CI/CD into AWS

got it, thanks!

**Comment by no13000** [comment]
@deld For the script (I wrote in nodejs env) should I merge into this project or into a separate project

**Comment by deld** [comment]
a separate project, I'll set it up for you.

**Comment by deld** [comment]
I just added you see you can check it in here - https://github.com/BaltimoreCity/meetup-register
